### ISSUE TITLE
Setting Heap Space

### ISSUE THREAD

**Issue by robertoschwald** [ponomandr/jmeter-idea-plugin#1]
When running JMeter via the plugin, I receive a heap error.

Is it possible to set the heap size somewhere?

**Comment by ponomandr** [comment]
Have you tried to specify "JVM parameters" in the run configuration?

![screenshot_13980](https://f.cloud.github.com/assets/1173842/916262/55763b0c-fe87-11e2-84ae-1ce4e51450d4.png)

**Comment by robertoschwald** [comment]
Thanks. It was too easy for me ;-)
