### ISSUE TITLE
Version 1.6 not compatible with IntelliJ running under Java 6

### ISSUE THREAD

**Issue by wfrantz** [ponomandr/jmeter-idea-plugin#2]
It looks like the latest version was built for Java 7, causing an exception on IDE startup if IntelliJ is configured to use Java 6 (which is the only version officially supported by JetBrains for OS X). Would it be feasible to provide an alternate Java 6 version?

**Comment by ponomandr** [comment]
The new version is deployed to plugin repository. Can you verify it works on OS X?

**Comment by wfrantz** [comment]
Works fine now. Thanks for the quick response!
